### ISSUE TITLE
Suggest a better way for to access the database

### ISSUE THREAD

**Issue by alllenshibu** [IEDCMEC/techno-event-management#49]
Suggest something better than writing raw SQL queries in the backend. The suggested method should be open source and stable (not in alpha testing or beta testing). Also provide some example code snippets along with your suggestion, preferably provide all the required code to change the existing system to the proposed system for at least one entity.

**Comment by rockingrohit9639** [comment]
Hey @alllenshibu 
You can either use [Sequelize](https://sequelize.org/) or if you wanna use the latest industry tech then you can go with [Prisma](https://www.prisma.io/). I have used it personally it has really great features.

**Comment by alllenshibu** [comment]
> Hey @alllenshibu You can either use [Sequelize](https://sequelize.org/) or if you wanna use the latest industry tech then you can go with [Prisma](https://www.prisma.io/). I have used it personally it has really great features.

Which one do you recommend? We want something stable and not in alpha/beta testing. We have tried using the Supabase client, but writing queries with join statements and such not-very-basic queries didn't go smoothly.

**Comment by rockingrohit9639** [comment]
> > Hey @alllenshibu You can either use [Sequelize](https://sequelize.org/) or if you wanna use the latest industry tech then you can go with [Prisma](https://www.prisma.io/). I have used it personally it has really great features.
> 
> Which one do you recommend? We want something stable and not in alpha/beta testing. We have tried using the Supabase client, but writing queries with join statements and such not-very-basic queries didn't go smoothly.

I have used `Prisma` in many of my projects and I have good experience with it.

**Comment by alllenshibu** [comment]
Okay.

So Prisma would be a good fit for this project.
